AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  sam-app
  Sample SAM Template for sam-app

Metadata:
  TemplateConfig:
    x-db-function-properties:
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetOneId
          - !Ref PrivateSubnetTwoId
          - !Ref PrivateSubnetThreeId
          - !Ref PrivateSubnetFourId
      Environment:
        Variables:
          DB_HOST: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:host}}"
          DB_USER: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:username}}"
          DB_PASSWORD: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:password}}"
          DB_PORT: 5432
          DB_NAME: !Ref DbName
      Layers:
        - !Ref RdsCertLayer
        - !Ref SharedUtilsLayer
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    # This configures API Gateway to answer the browser's "OPTIONS" check
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'" # <--- Note the quoting: "'*'"

Parameters:
  CognitoUserPoolArn:
    Type: String
    Description: The ARN of the pre-existing Cognito User Pool
  DbName:
    Type: String
    Description: The database name to connect to
    Default: postgres
  LambdaSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The Security Group to attach to the Lambda functions
  PrivateSubnetOneId:
    Type: AWS::EC2::Subnet::Id
    Description: A private subnet ID for the lambda
  PrivateSubnetTwoId:
    Type: AWS::EC2::Subnet::Id
    Description: A private subnet ID for the lambda
  PrivateSubnetThreeId:
    Type: AWS::EC2::Subnet::Id
    Description: A private subnet ID for the lambda
  PrivateSubnetFourId:
    Type: AWS::EC2::Subnet::Id
    Description: A private subnet ID for the lambda

Resources:
  RdsCertLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: RdsCertLayer
      ContentUri: layers/certs/
      CompatibleRuntimes:
        - nodejs22.x

  SharedUtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: SharedUtilsLayer
      ContentUri: layers/shared/
      CompatibleRuntimes:
        - nodejs22.x
    Metadata:
      BuildMethod: nodejs22.x
      BuildArchitecture: x86_64

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS,PATCH'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'" # <--- Note the quoting: "'*'"
      Auth:
        Authorizers:
          MyCognitoAuthorizer:
            Type: COGNITO_USER_POOLS
            UserPoolArn: !Ref CognitoUserPoolArn
        DefaultAuthorizer: MyCognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false

  MatchScoringFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetOneId
          - !Ref PrivateSubnetTwoId
          - !Ref PrivateSubnetThreeId
          - !Ref PrivateSubnetFourId
      Environment:
        Variables:
          DB_HOST: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:host}}"
          DB_USER: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:username}}"
          DB_PASSWORD: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:password}}"
          DB_PORT: 5432
          DB_NAME: !Ref DbName
      Layers:
        - !Ref RdsCertLayer
        - !Ref SharedUtilsLayer
      CodeUri: match-scoring-functions/
      Handler: app.lambdaHandler
      Events:
        CreateMatch:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref MyApi
            Path: /scoring/createMatch
            Method: post
        StartMatchScoring:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /scoring/{matchId}/startScoring
            Method: patch
        AddEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /scoring/{matchId}/addEvent
            Method: post
    Metadata:
      # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  # ----------------------------------------------------------
  # User Functions
  # ----------------------------------------------------------

  UserDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetOneId
          - !Ref PrivateSubnetTwoId
          - !Ref PrivateSubnetThreeId
          - !Ref PrivateSubnetFourId
      Environment:
        Variables:
          DB_HOST: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:host}}"
          DB_USER: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:username}}"
          DB_PASSWORD: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:password}}"
          DB_PORT: 5432
          DB_NAME: !Ref DbName
      Layers:
        - !Ref RdsCertLayer
        - !Ref SharedUtilsLayer
      CodeUri: users-functions/
      Handler: app.lambdaHandler
      Events:
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /users/auth/signup
            Method: put
        GetUserProfile:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /users/profile
            Method: get
        UpdateUserProfile:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /users/profile
            Method: patch
    Metadata:
      # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
  # ----------------------------------------------------------
  # Tournament Functions
  # ----------------------------------------------------------
  TournamentDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetOneId
          - !Ref PrivateSubnetTwoId
          - !Ref PrivateSubnetThreeId
          - !Ref PrivateSubnetFourId
      Environment:
        Variables:
          DB_HOST: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:host}}"
          DB_USER: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:username}}"
          DB_PASSWORD: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:password}}"
          DB_PORT: 5432
          DB_NAME: !Ref DbName
      Layers:
        - !Ref RdsCertLayer
        - !Ref SharedUtilsLayer
      CodeUri: tournaments-functions/
      Handler: app.lambdaHandler
      Events:
        GetAllTournaments:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /tournaments
            Method: get
        GetTournament:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /tournaments/{tournamentId}
            Method: get
        GetTournamentSeasons:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /tournaments/{tournamentId}/seasons
            Method: get
    Metadata:
      # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
  # ----------------------------------------------------------
  # Season Functions
  # ----------------------------------------------------------
  SeasonsDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetOneId
          - !Ref PrivateSubnetTwoId
          - !Ref PrivateSubnetThreeId
          - !Ref PrivateSubnetFourId
      Environment:
        Variables:
          DB_HOST: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:host}}"
          DB_USER: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:username}}"
          DB_PASSWORD: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:password}}"
          DB_PORT: 5432
          DB_NAME: !Ref DbName
      Layers:
        - !Ref RdsCertLayer
        - !Ref SharedUtilsLayer
      CodeUri: seasons-functions/
      Handler: app.lambdaHandler
      Events:
        GetSeason:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /seasons/{seasonId}
            Method: get
    Metadata:
      # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
  # ----------------------------------------------------------
  # Match Functions
  # ----------------------------------------------------------
  MatchDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetOneId
          - !Ref PrivateSubnetTwoId
          - !Ref PrivateSubnetThreeId
          - !Ref PrivateSubnetFourId
      Environment:
        Variables:
          DB_HOST: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:host}}"
          DB_USER: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:username}}"
          DB_PASSWORD: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:password}}"
          DB_PORT: 5432
          DB_NAME: !Ref DbName
      Layers:
        - !Ref RdsCertLayer
        - !Ref SharedUtilsLayer
      CodeUri: matches-functions/
      Handler: app.lambdaHandler
      Events:
        GetHomeFeedMatches:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /matches/feed
            Method: get
        GetMatch:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /matches/{matchId}
            Method: get
    Metadata:
      # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
  # ----------------------------------------------------------
  # Fantasy Team Functions
  # ----------------------------------------------------------
  FantasyTeamsDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetOneId
          - !Ref PrivateSubnetTwoId
          - !Ref PrivateSubnetThreeId
          - !Ref PrivateSubnetFourId
      Environment:
        Variables:
          DB_HOST: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:host}}"
          DB_USER: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:username}}"
          DB_PASSWORD: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:password}}"
          DB_PORT: 5432
          DB_NAME: !Ref DbName
      Layers:
        - !Ref RdsCertLayer
        - !Ref SharedUtilsLayer
      CodeUri: fantasy-teams-functions/
      Handler: app.lambdaHandler
      Events:
        GetUsersFantasyTeams:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /fantasy-teams/user
            Method: get
        GetFantasyTeamsInLeague:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /fantasy-teams
            Method: get
        GetFantasyTeam:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /fantasy-teams/{fantasyTeamId}
            Method: get
    Metadata:
      # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
  # ----------------------------------------------------------
  # League Functions
  # ----------------------------------------------------------
  LeagueDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetOneId
          - !Ref PrivateSubnetTwoId
          - !Ref PrivateSubnetThreeId
          - !Ref PrivateSubnetFourId
      Environment:
        Variables:
          DB_HOST: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:host}}"
          DB_USER: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:username}}"
          DB_PASSWORD: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:password}}"
          DB_PORT: 5432
          DB_NAME: !Ref DbName
      Layers:
        - !Ref RdsCertLayer
        - !Ref SharedUtilsLayer
      CodeUri: league-functions/
      Handler: app.lambdaHandler
      Events:
        GetUserLeagues:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /leagues
            Method: get
        GetLeagueById:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /leagues/{leagueId}
            Method: get
        GetDefaultScoringRules:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /leagues/scoring-rules
            Method: get
        GetScoringRules:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /leagues/{leagueId}/scoring-rules
            Method: get
        CreateLeague:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /leagues
            Method: post
    Metadata:
      # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  MatchupDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetOneId
          - !Ref PrivateSubnetTwoId
          - !Ref PrivateSubnetThreeId
          - !Ref PrivateSubnetFourId
      Environment:
        Variables:
          DB_HOST: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:host}}"
          DB_USER: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:username}}"
          DB_PASSWORD: "{{resolve:secretsmanager:sixers-app/db-creds:SecretString:password}}"
          DB_PORT: 5432
          DB_NAME: !Ref DbName
      Layers:
        - !Ref RdsCertLayer
        - !Ref SharedUtilsLayer
      CodeUri: matchup-functions/
      Handler: app.lambdaHandler
      Events:
        GetMatchupById:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /matchups/{matchUpId}
            Method: get
        GetMatchUpFeed:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /matchups/feed
            Method: get
    Metadata:
      # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
