AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  sam-app
  Sample SAM Template for sam-app

Metadata:
  TemplateConfig:
    x-db-function-properties:
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetOneId
          - !Ref PrivateSubnetTwoId
          - !Ref PrivateSubnetThreeId
          - !Ref PrivateSubnetFourId
      Environment:
        Variables:
          DB_HOST: '{{resolve:secretsmanager:sixers-app/db-creds:SecretString:host}}'
          DB_USER: '{{resolve:secretsmanager:sixers-app/db-creds:SecretString:username}}'
          DB_PASSWORD: '{{resolve:secretsmanager:sixers-app/db-creds:SecretString:password}}'
          DB_PORT: 5432
          DB_NAME: !Ref DbName
      Layers:
        - !Ref RdsCertLayer
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    # This configures API Gateway to answer the browser's "OPTIONS" check
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'" # <--- Note the quoting: "'*'"

Parameters:
  CognitoUserPoolArn:
    Type: String
    Description: The ARN of the pre-existing Cognito User Pool
  DbName:
    Type: String
    Description: The database name to connect to
    Default: postgres
  LambdaSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The Security Group to attach to the Lambda functions
  PrivateSubnetOneId:
    Type: AWS::EC2::Subnet::Id
    Description: A private subnet ID for the lambda
  PrivateSubnetTwoId:
    Type: AWS::EC2::Subnet::Id
    Description: A private subnet ID for the lambda
  PrivateSubnetThreeId:
    Type: AWS::EC2::Subnet::Id
    Description: A private subnet ID for the lambda
  PrivateSubnetFourId:
    Type: AWS::EC2::Subnet::Id
    Description: A private subnet ID for the lambda

Resources:
  RdsCertLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: RdsCertLayer
      ContentUri: layers/certs/
      CompatibleRuntimes:
        - nodejs22.x
  
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        Authorizers:
          MyCognitoAuthorizer:
            Type: COGNITO_USER_POOLS
            UserPoolArn: !Ref CognitoUserPoolArn
        DefaultAuthorizer: MyCognitoAuthorizer

  CreateFantasyUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      VpcConfig: 
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetOneId
          - !Ref PrivateSubnetTwoId
          - !Ref PrivateSubnetThreeId
          - !Ref PrivateSubnetFourId
      Environment:
        Variables:
          DB_HOST: '{{resolve:secretsmanager:sixers-app/db-creds:SecretString:host}}'
          DB_USER: '{{resolve:secretsmanager:sixers-app/db-creds:SecretString:username}}'
          DB_PASSWORD: '{{resolve:secretsmanager:sixers-app/db-creds:SecretString:password}}'
          DB_PORT: 5432
          DB_NAME: !Ref DbName
      Layers:
        - !Ref RdsCertLayer
      CodeUri: auth-create-user/
      Handler: app.lambdaHandler
      Events:
        CreateUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref MyApi
            Path: /auth/createUser
            Method: post
    Metadata:
      # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts  

  SeasonInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      VpcConfig: 
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetOneId
          - !Ref PrivateSubnetTwoId
          - !Ref PrivateSubnetThreeId
          - !Ref PrivateSubnetFourId
      Environment:
        Variables:
          DB_HOST: '{{resolve:secretsmanager:sixers-app/db-creds:SecretString:host}}'
          DB_USER: '{{resolve:secretsmanager:sixers-app/db-creds:SecretString:username}}'
          DB_PASSWORD: '{{resolve:secretsmanager:sixers-app/db-creds:SecretString:password}}'
          DB_PORT: 5432
          DB_NAME: !Ref DbName
      Layers:
        - !Ref RdsCertLayer
      CodeUri: season-info/
      Handler: app.lambdaHandler
      Events:
        SeasonInfo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref MyApi
            Path: /season/{seasonId}
            Method: get
    Metadata:
      # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts  

  TournamentInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      VpcConfig: 
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetOneId
          - !Ref PrivateSubnetTwoId
          - !Ref PrivateSubnetThreeId
          - !Ref PrivateSubnetFourId
      Environment:
        Variables:
          DB_HOST: '{{resolve:secretsmanager:sixers-app/db-creds:SecretString:host}}'
          DB_USER: '{{resolve:secretsmanager:sixers-app/db-creds:SecretString:username}}'
          DB_PASSWORD: '{{resolve:secretsmanager:sixers-app/db-creds:SecretString:password}}'
          DB_PORT: 5432
          DB_NAME: !Ref DbName
      Layers:
        - !Ref RdsCertLayer
      CodeUri: tournament-info/
      Handler: app.lambdaHandler
      Events:
        TournamentInfo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref MyApi
            Path: /tournament/{tournamentId}
            Method: get
    Metadata:
      # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts 

  UpdateProfileDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      VpcConfig: 
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
        SubnetIds:
          - !Ref PrivateSubnetOneId
          - !Ref PrivateSubnetTwoId
          - !Ref PrivateSubnetThreeId
          - !Ref PrivateSubnetFourId
      Environment:
        Variables:
          DB_HOST: '{{resolve:secretsmanager:sixers-app/db-creds:SecretString:host}}'
          DB_USER: '{{resolve:secretsmanager:sixers-app/db-creds:SecretString:username}}'
          DB_PASSWORD: '{{resolve:secretsmanager:sixers-app/db-creds:SecretString:password}}'
          DB_PORT: 5432
          DB_NAME: !Ref DbName
      Layers:
        - !Ref RdsCertLayer
      CodeUri: update-profile-info/
      Handler: app.lambdaHandler
      Events:
        UpdateProfile:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref MyApi
            Path: /profile/{userid}
            Method: put
    Metadata:
      # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts  
